Home task_v2_01
pluhin/sa.it-academy.by pull request #1031
Opened 2020-11-24 20:21 UTC by Aleksey-Smouzh

I'm not sure that can be right

2020-11-25 22:51 UTC, pluhin requested changes

2020-11-25 22:51 UTC, pluhin commented on ASmouzh/Htask_01/file1.txt
> +Операционная система,
What is it?

2020-11-25 22:51 UTC, pluhin commented on ASmouzh/Htask_v2_01/list_of_commamds
> + 133  cd gitTest
Please use github markdown to formatting your reports: https://guides.github.com/features/mastering-markdown/

2020-11-26 06:39 UTC, Aleksey-Smouzh commented
About "ASmouzh/Htask_01/file1.txt" I forgot part of home task what I needed to do, and I wrote something to make sure the file wasn't empty. 26.11.2020, 01:51, "Siarhei Pishchyk" <notifications@github.com>: @pluhin requested changes on this pull request.In ASmouzh/Htask_01/file1.txt:> @@ -0,0 +1,5 @@
+Операционная система,
What is it?In ASmouzh/Htask_v2_01/list_of_commamds:> @@ -0,0 +1,143 @@
+ 133  cd gitTest
Please use github markdown to formatting your reports: https://guides.github.com/features/mastering-markdown/—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-30 07:43 UTC, pluhin requested changes

2020-11-30 07:43 UTC, pluhin commented on ASmouzh/Htask_01/ReadME.md
> +$ Пустой локальный репозиторий инициалирует  (git init) папку <системный файл (. git)>
Please use github markdown for your reports

2020-11-30 07:43 UTC, pluhin commented on ASmouzh/Htask_v2_01/list_of_commamds
> +
Missing output for list of commit for each branch in final

2020-12-02 14:34 UTC, pluhin requested changes

2020-12-02 14:34 UTC, pluhin commented on ASmouzh/Htask_01/ReadME.md
> +#Readme.md
Missing space between # and header

2020-12-02 14:34 UTC, pluhin commented on ASmouzh/Htask_01/ReadME.md
> +$ Пустой локальный репозиторий инициалирует  (git init) папку <системный файл (. git)>
Please remove $ in front of each "human" lines and use code block for code

2020-12-10 13:43 UTC, pluhin commented
Are there any changes expected?

2020-12-10 14:02 UTC, Aleksey-Smouzh commented
Yes. it will be changed but not now. 10.12.2020, 16:43, "Siarhei Pishchyk" <notifications@github.com>: Are there any changes expected?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-19 16:15 UTC, closed without merging