my homework 2 and 3
pluhin/sa.it-academy.by pull request #1051
Opened 2020-12-07 20:30 UTC by andbelvg

2020-12-10 13:41 UTC, pluhin requested changes
Please use correct github markdown

2020-12-21 11:49 UTC, pluhin commented
Any updates?

2020-12-28 21:25 UTC, andbelvg commented
Markdown updated

2020-12-29 09:31 UTC, pluhin commented
Please squash all your commits

2020-12-29 09:32 UTC, pluhin commented
I do not see links to your external repositories for 3th task

2020-12-29 09:33 UTC, pluhin requested changes

2020-12-29 09:33 UTC, pluhin commented on Andrei_Dubina/3 - Git remote/3 - Git remote.md
> +git remote add origin git@github.com:andbelvg/03-git-homework.git
Please use code section for code

2020-12-29 09:33 UTC, pluhin commented on Andrei_Dubina/3 - Git remote/3 - Git remote.md
> +by using  git push -u origin --all
Please use code section for code

2020-12-29 09:33 UTC, pluhin commented on Andrei_Dubina/3 - Git remote/3 - Git remote.md
> +<https://github.com/andbelvg/03-git-homework|andbelvg/03-git-homework>andbelvg/03-git-homework
What is it. It is broken, I mean url

2021-02-19 16:15 UTC, closed without merging