Korolev Md sa2 16 21
pluhin/sa.it-academy.by pull request #1091
Opened 2021-02-23 16:57 UTC by Korolev731

2021-02-23 19:04 UTC, pluhin requested changes

2021-02-23 19:04 UTC, pluhin commented on README.md
> +# 1
Please remove this changes

2021-02-23 19:04 UTC, pluhin commented on readme.md
> +##1 commit
Please remove this file

2021-02-24 09:41 UTC, Korolev731 commented on readme.md
> +##1 commit
fixed

2021-02-24 09:41 UTC, Korolev731 commented on README.md
> +# 1
fixed

2021-02-24 15:21 UTC, pluhin requested changes
Do not remove not your files. It is not good for shared project

2021-02-24 18:24 UTC, closed without merging