Add DZ 04 vagrant
pluhin/sa.it-academy.by pull request #1102
Opened 2021-02-26 12:37 UTC by MsWik

Adding homework on vagrant

2021-02-28 17:07 UTC, pluhin requested changes

2021-02-28 17:07 UTC, pluhin commented on biaspaltsau_a/04. Vagrant/README.md
> +# 04.Vagrant
Please remove white-spaces from folder name

2021-03-01 04:56 UTC, MsWik commented on biaspaltsau_a/04. Vagrant/README.md
> +# 04.Vagrant
fixed

2021-03-01 13:44 UTC, pluhin approved these changes
Good, approved

2021-03-01 13:44 UTC, merged