Ansible workshop
pluhin/sa.it-academy.by pull request #1189
Opened 2021-04-06 15:18 UTC by AleksandMur

Could you chek my home task

2021-04-08 10:38 UTC, pluhin requested changes

2021-04-08 10:38 UTC, pluhin commented on Aleksandr_Murygin/14.Ansible_Workshop/WS/roles/mysql/templates/database.yml.j2
> +### {{ ansible_managed }}
This template belongs to application tasks, please move it to application role

2021-04-08 12:06 UTC, AleksandMur commented
corrected

2021-04-08 12:27 UTC, pluhin commented on Aleksandr_Murygin/14.Ansible_Workshop/WS/roles/mysql/templates/database.yml.j2
> +### {{ ansible_managed }}
@AleksandMur

Did you test it? Please provide output

2021-04-08 18:05 UTC, AleksandMur commented
corrected v0.2

2021-04-10 19:20 UTC, pluhin approved these changes
Good, approved

2021-04-10 19:20 UTC, merged