14.ansible.ws
pluhin/sa.it-academy.by pull request #1198
Opened 2021-04-11 16:53 UTC by iryna-kurhuzenkava

2021-04-12 08:03 UTC, iryna-kurhuzenkava commented
14.ansible.ws + 12.ansible.run

2021-04-12 14:19 UTC, pluhin requested changes

2021-04-12 14:19 UTC, pluhin commented on iryna_kurhuzenkava/14.ansible.ws/ans_ws/roles/redmine_db/tasks/main.yaml
> +- name: Config database
Please move this task to app role, and redeploy it to check if everything is correct

2021-04-13 11:43 UTC, pluhin requested changes

2021-04-13 11:43 UTC, pluhin commented on iryna_kurhuzenkava/14.ansible.ws/ans_ws/roles/redmine_app/tasks/main.yaml
> +- name: Config database
Why is this here? Please put in correct place. You do deployment of application, and in the end of deployment copy database connection settings. This is wrong

2021-04-13 13:56 UTC, pluhin approved these changes
Good, approved

2021-04-13 13:56 UTC, merged