№1
pluhin/sa.it-academy.by pull request #1264
Opened 2021-06-17 10:09 UTC by Zhenyakuch

2021-06-17 12:24 UTC, pluhin requested changes

2021-06-17 12:24 UTC, pluhin commented on Evgeniya_Pehota/02.Git.Local/README.md
> +  494  cd C:\academy.by
Please use git markdown, for your report

2021-06-17 12:24 UTC, pluhin commented on Evgeniya_Pehota/02.Git.Local/README.md
> +  545  history
Missing list of commits for each branches in report

2021-06-17 13:42 UTC, pluhin commented
Please, change name of PR, the mean `№` need to replace

2021-06-17 14:04 UTC, pluhin commented
Please squash commits to one or two commits

2021-06-18 07:08 UTC, closed without merging

2021-06-18 07:09 UTC, Zhenyakuch commented
/