04.Vagrant
pluhin/sa.it-academy.by pull request #1300
Opened 2021-06-25 08:14 UTC by Zhenyakuch

2021-06-25 14:34 UTC, pluhin requested changes

2021-06-25 14:34 UTC, pluhin commented on Evgeniya_Pehota/04.Vagrant/04.Vagrant.md
> +      sudo useradd -m updater
Please remove sudo, it is not needed

2021-06-25 14:34 UTC, pluhin commented on Evgeniya_Pehota/04.Vagrant/04.Vagrant.md
> +      sudo echo "updater:vagrant" | chpasswd
Please remove sudo

2021-06-28 06:54 UTC, Zhenyakuch commented on Evgeniya_Pehota/04.Vagrant/04.Vagrant.md
> +      sudo echo "updater:vagrant" | chpasswd
fixed

2021-06-28 07:23 UTC, pluhin approved these changes
Good, approved

2021-06-28 07:23 UTC, merged