Homework.07.Ansible.Cruize
pluhin/sa.it-academy.by pull request #1316
Opened 2021-07-02 07:49 UTC by AndreiAkhrymenko

2021-07-02 17:18 UTC, pluhin requested changes
Please use one template for all hosts

2021-07-03 11:09 UTC, AndreiAkhrymenko commented
1. made 1 template for CFGs VS 4 files
2. added few loops for repeated tasks

2021-07-05 11:23 UTC, pluhin requested changes

2021-07-05 11:23 UTC, pluhin commented on aakhrymenko/07.Ansible.Cruize/Ansible/roles/test_role1_nginx/tasks/main.yaml
> +- name: Make Link site1
Should be on task with template for site config

2021-07-05 15:52 UTC, pluhin approved these changes
Good, approved

2021-07-05 15:52 UTC, merged