06. Ansible.run
pluhin/sa.it-academy.by pull request #1330
Opened 2021-07-08 21:53 UTC by Zhenyakuch

2021-07-09 12:25 UTC, pluhin requested changes
Remove whitespace from folder path, or replace by `_`

2021-07-09 12:25 UTC, pluhin commented on Evgeniya_Pehota/06. Ansible.run/06. Ansible.run.md
> +ok: [work_01] => (item=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD9eMhBCgVVDnENFCd1dz7jFtiPjSa8rqaJYuga63Ll89DZ1ynHnJ49Inn9PDwGPWIr41eFB75wWAASXJ+NaZh7Ly1gyCA+PACjZkYILf/QecoJhOs+xj4X79xvnyt5Tlj0ndMhUPHa
Please remove sensitive data from PR

2021-07-09 12:25 UTC, pluhin commented on Evgeniya_Pehota/06. Ansible.run/06. Ansible.run.md
> +ok: [work_02] => (item=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD9eMhBCgVVDnENFCd1dz7jFtiPjSa8rqaJYuga63Ll89DZ1ynHnJ49Inn9PDwGPWIr41eFB75wWAASXJ+NaZh7Ly1gyCA+PACjZkYILf/QecoJhOs+xj4X79xvnyt5Tlj0ndMhUPHa
Please remove sensitive data from PR

2021-07-12 06:04 UTC, Zhenyakuch commented on Evgeniya_Pehota/06. Ansible.run/06. Ansible.run.md
> +ok: [work_01] => (item=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD9eMhBCgVVDnENFCd1dz7jFtiPjSa8rqaJYuga63Ll89DZ1ynHnJ49Inn9PDwGPWIr41eFB75wWAASXJ+NaZh7Ly1gyCA+PACjZkYILf/QecoJhOs+xj4X79xvnyt5Tlj0ndMhUPHa
fixed

2021-07-12 06:04 UTC, Zhenyakuch commented on Evgeniya_Pehota/06. Ansible.run/06. Ansible.run.md
> +ok: [work_02] => (item=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD9eMhBCgVVDnENFCd1dz7jFtiPjSa8rqaJYuga63Ll89DZ1ynHnJ49Inn9PDwGPWIr41eFB75wWAASXJ+NaZh7Ly1gyCA+PACjZkYILf/QecoJhOs+xj4X79xvnyt5Tlj0ndMhUPHa
fixed

2021-07-12 07:45 UTC, pluhin requested changes
Please remove white-space from names of folders and files

2021-07-12 08:48 UTC, closed without merging