10.Docker-compose_terraform
pluhin/sa.it-academy.by pull request #1343
Opened 2021-07-13 21:47 UTC by chulets

2021-07-14 22:57 UTC, pluhin requested changes
Please, remove radarr and sonarr config folders from PR

2021-07-15 06:28 UTC, chulets commented
Configs were removed

2021-07-15 15:43 UTC, pluhin approved these changes

2021-07-15 15:43 UTC, pluhin commented on Hanna_Chulets/10.Docker-compose_terraform/config/sonarr/.config/.mono/keypairs/[1][98f3a7e3-0d6e-f432-8a18-e1144b53633f][-1].xml
> +		<RSAKeyValue><Modulus>m45AUotYlOOidt38d4e4J6UU6yB9jE3D0khSgzlBZkh6gEOOaEhEMzbbx2du2F2kRwap2Lo6olgAkFv9ek0e/gRVT24EhZFBLQ5bIBEzgHj6DNMIsLCBuRELSayq+eqAon3JXF4KSYqLI/U+RuoxZoP2tgGajdsO16dc5CqoRoiLr4O
Please remove rsa key

2021-07-15 15:43 UTC, merged