16.Jenkins.Start
pluhin/sa.it-academy.by pull request #1391
Opened 2021-08-05 14:49 UTC by chulets

2021-08-06 11:18 UTC, pluhin requested changes

2021-08-06 11:18 UTC, pluhin commented on Hanna_Chulets/16.Jenkins.Start/node/authorized_keys
> +ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1zeCH6wgW7ZL8Dv46YhSUYYUi8fNm+44WdQ57auCeNgwOR3MiaQIgmySefWtDHBLLGqa/lAhnlW/h4j29sNrsKHZMwCcYyQseD8ILpOftfxBB4qH8oHGQ7LZuXpWuGdcrdky0r24rqGwxZRvhHgUz0L/IkIG8S1f
Please remove this key from PR

2021-08-06 18:13 UTC, chulets commented on Hanna_Chulets/16.Jenkins.Start/node/authorized_keys
> +ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1zeCH6wgW7ZL8Dv46YhSUYYUi8fNm+44WdQ57auCeNgwOR3MiaQIgmySefWtDHBLLGqa/lAhnlW/h4j29sNrsKHZMwCcYyQseD8ILpOftfxBB4qH8oHGQ7LZuXpWuGdcrdky0r24rqGwxZRvhHgUz0L/IkIG8S1f
Removed , please check

2021-08-07 15:27 UTC, pluhin approved these changes
Good, approved

2021-08-07 15:27 UTC, merged