Md sa2 18 21
pluhin/sa.it-academy.by pull request #1444
Opened 2021-09-24 21:03 UTC by mikevoice

home work 02.git

2021-09-26 18:18 UTC, pluhin requested changes

2021-09-26 18:18 UTC, pluhin commented on Mikhail_Murashevich/02.Git.Local/02.Git.md
> +'''bash
Wrong github markdown, please check your quotes

2021-09-27 05:40 UTC, mikevoice commented on Mikhail_Murashevich/02.Git.Local/02.Git.md
> +'''bash
changed quotes

2021-09-27 14:39 UTC, pluhin approved these changes
Good, approved

2021-09-27 14:39 UTC, merged