02.Git.Local_Maxim_Radaman
pluhin/sa.it-academy.by pull request #1541
Opened 2022-01-17 16:06 UTC by redman27

02.Git.Local_Maxim_Radaman

2022-01-17 16:48 UTC, pluhin requested changes
Please leave only report in your PR

2022-01-17 17:45 UTC, redman27 commented
files removed, also change syntax in report file

2022-01-17 17:47 UTC, pluhin requested changes

2022-01-17 17:47 UTC, pluhin commented on Maxim_Radaman/02.Git.Local/02.GIT.Local.md
> +<<<<<<< HEAD
@redman27 

Looks like conflict?

2022-01-17 17:56 UTC, redman27 commented on Maxim_Radaman/02.Git.Local/02.GIT.Local.md
> +<<<<<<< HEAD
fixed

2022-01-18 21:42 UTC, pluhin approved these changes
Good, approved

2022-01-18 21:42 UTC, merged