06.Ansible.start Maxim Radaman
pluhin/sa.it-academy.by pull request #1585
Opened 2022-02-02 11:40 UTC by redman27

06.Ansible.start Maxim Radaman

2022-02-02 17:36 UTC, pluhin requested changes
Your last home works copy of Ivan Ustinovich works

Please do your work more uniq

2022-02-02 17:37 UTC, pluhin requested changes

2022-02-02 17:37 UTC, pluhin commented on Maxim_Radaman/06.Ansible/index.html
> +Ivan_Ustinovich
:)

2022-02-02 18:28 UTC, redman27 commented on Maxim_Radaman/06.Ansible/index.html
> +Ivan_Ustinovich
oops

2022-02-03 16:55 UTC, pluhin approved these changes
Ok, accepted

2022-02-03 16:55 UTC, merged