Hometask 02.GIT.Local Andrei_Bakaushyn
pluhin/sa.it-academy.by pull request #1672
Opened 2022-04-30 16:59 UTC by AndreiBakaushyn

Good day Sergey. Initially, I misunderstood the tasks, and cloned your repository to my local machine, did all the tasks, and then tried to push them to you on the remote repository in main)) (Erorr 403), that was wery fun ,  then made a fork, and sent a history file).  
With best regards, 
Andrei Bakaushyn

2022-04-30 17:34 UTC, pluhin requested changes
Missing log of commits for each branch, please add to the end of your report

2022-04-30 17:34 UTC, pluhin commented on Andrei_Bakaushyn/02.Git.Local/02.GIT.local.md
> +  346  history
Please close code section

2022-05-01 09:01 UTC, AndreiBakaushyn commented
Fixed report

2022-05-01 11:18 UTC, pluhin requested changes
Could you please use git markdown for git log output too

2022-05-02 08:45 UTC, AndreiBakaushyn commented
Good day !, 
Covered paragraphs, headings, and corresponding bash command sessions with markdown in my Report

2022-05-05 20:49 UTC, closed without merging