addGitOPS
pluhin/sa.it-academy.by pull request #1690
Opened 2022-05-04 16:55 UTC by mnogosemok

2022-05-05 12:29 UTC, pluhin requested changes
remove white-space from folder name

2022-05-05 12:29 UTC, pluhin commented on Vadim_Shishlo/04. GitOPS/READMI.md
> +# 04.GitOPS
Please correct name of the file (READM**E**.md)

2022-05-05 15:01 UTC, mnogosemok reviewed
add

2022-05-06 01:03 UTC, pluhin approved these changes
Good, approved

2022-05-06 01:03 UTC, merged