addargocd
pluhin/sa.it-academy.by pull request #1830
Opened 2022-06-04 18:42 UTC by mnogosemok

2022-06-05 15:51 UTC, pluhin requested changes

2022-06-05 15:51 UTC, pluhin commented on Vadim_Shishlo/14.Kubernetes application deployment/README.md
> +  password: 135246proprprEfasde4
It is not base64

2022-06-06 12:47 UTC, mnogosemok commented
Add14

2022-06-06 13:09 UTC, mnogosemok commented
Fixed by 14.k8s

2022-06-06 15:27 UTC, merged