Homework 13.Kubernetes.Helm
pluhin/sa.it-academy.by pull request #1866
Opened 2022-06-13 22:29 UTC by Vigovskiyy

2022-06-14 16:34 UTC, pluhin requested changes

2022-06-14 16:34 UTC, pluhin commented on Yuri_Vygovskiy/12.Kubernetes.First/runner/secret.yaml
> +<<<<<<< HEAD
Please clean here, looks like conflict's artefacts

2022-06-14 17:55 UTC, Vigovskiyy commented on Yuri_Vygovskiy/12.Kubernetes.First/runner/secret.yaml
> +<<<<<<< HEAD
done

2022-06-14 18:17 UTC, pluhin commented
@Vigovskiyy 

You have deleted this file from PR but not from the history of your commits, this commit still contains your secret: [delete secret](https://github.com/pluhin/sa.it-academy.by/pull/1866/commits/6550f6b9f1d8c907950b918e4a8017fd7821ee6d)

it will be visible all time 

I explained theses solutions on our lessons:
- you can fixup (squash) your commit to remove this secret from the history
- revert  all commis from the head include this with secret, then add new one without this secrets

2022-06-15 23:02 UTC, Vigovskiyy commented
I tried to make squash and fixup of problematic commits, but this greatly affected the entire commit history in my folder, after which I returned everything to its original state, but now git guardian sees 4 uncovered secrets. Could you help solve this problem, since I'm afraid to make changes already in order to avoid larger problems?

2022-06-17 07:04 UTC, merged