11.K8s homework
pluhin/sa.it-academy.by pull request #2028
Opened 2022-08-24 19:44 UTC by S-Stepanenko

Homework

2022-08-25 00:33 UTC, pluhin requested changes
Please remove sensitive data from your PR

2022-08-25 15:24 UTC, S-Stepanenko commented
dell key

2022-08-25 18:49 UTC, S-Stepanenko commented
Git reset and delete key

2022-08-26 12:19 UTC, pluhin commented
private keys still there

2022-08-27 09:09 UTC, closed without merging