Added HW:15,16
pluhin/sa.it-academy.by pull request #2089
Opened 2022-09-26 08:23 UTC by agbusko

2022-09-27 07:31 UTC, pluhin commented
@agbusko 
Could you please move reports in your folder

2022-09-27 07:31 UTC, pluhin requested changes
Wrong folder position, please correct

2022-09-27 08:20 UTC, agbusko commented
@pluhin Исправил, спасибо

2022-09-28 23:31 UTC, pluhin approved these changes
Good, approved

2022-09-28 23:31 UTC, merged