02.GIT.local
pluhin/sa.it-academy.by pull request #2113
Opened 2022-11-18 16:42 UTC by Haroshka

2022-11-18 16:46 UTC, pluhin requested changes

2022-11-18 16:46 UTC, pluhin commented on Ivan-Haroshka/02. GIT. Local/README.md
> +02.GIT.local
Missing list of commits for each branch

2022-11-18 16:46 UTC, pluhin commented on Ivan-Haroshka/02. GIT. Local/README.md
> +02.GIT.local
Should be header

2022-11-19 13:11 UTC, Haroshka commented on Ivan-Haroshka/02. GIT. Local/README.md
> +02.GIT.local
list added

2022-11-19 13:11 UTC, Haroshka commented on Ivan-Haroshka/02. GIT. Local/README.md
> +02.GIT.local
header added

2022-11-20 06:07 UTC, pluhin approved these changes
Good, approved

2022-11-20 06:07 UTC, merged