Md sa2 23 23
pluhin/sa.it-academy.by pull request #2285
Opened 2023-02-23 13:29 UTC by ivankuzminn

2023-02-23 16:50 UTC, pluhin requested changes
Please squash your commits

2023-02-24 08:00 UTC, ivankuzminn commented
> Please squash your commits

already done

2023-02-24 18:52 UTC, pluhin requested changes

2023-02-24 18:52 UTC, pluhin commented on demo/02.Git/README.md
> +# 02.Git
This file should not be in PR, please resolve, probably need to rebase

2023-02-26 19:52 UTC, merged