Md sa2 23 23 - 05 and 06 HW
pluhin/sa.it-academy.by pull request #2333
Opened 2023-03-06 08:43 UTC by julietredk

2023-03-07 14:11 UTC, pluhin requested changes

2023-03-07 14:11 UTC, pluhin commented on Yulia_Redkova/06.Ansible_workshop/playbook_nginx.yaml
> +      ansible.builtin.template:
Do not duplicate code, especially when you use template modue

2023-03-07 14:11 UTC, pluhin commented on Yulia_Redkova/06.Ansible_workshop/playbook_nginx.yaml
> +      ansible.builtin.replace:
Please use template module here, you can generate config files

2023-03-09 11:42 UTC, julietredk commented
fixed.

2023-03-09 15:43 UTC, pluhin approved these changes
Good, approved

2023-03-09 15:43 UTC, merged