04. GitOps
pluhin/sa.it-academy.by pull request #2334
Opened 2023-03-06 12:12 UTC by kurlenka-d

2023-03-07 15:06 UTC, pluhin requested changes

2023-03-07 15:06 UTC, pluhin commented on Dzmitry_Kurlenka/04.Git/tab.yaml
> +                pull_request:
please correct indents

2023-03-07 22:16 UTC, kurlenka-d commented on Dzmitry_Kurlenka/04.Git/tab.yaml
> +                pull_request:
indents changed

2023-03-09 05:40 UTC, pluhin approved these changes

2023-03-09 05:40 UTC, merged