13.Kube.Helm report
pluhin/sa.it-academy.by pull request #2434
Opened 2023-04-06 13:03 UTC by evkenny

2023-04-06 18:30 UTC, pluhin requested changes
please remove secrets from PR

2023-04-07 05:12 UTC, evkenny commented
removed

2023-04-07 16:40 UTC, pluhin commented
> removed

no, secret sill in your commits

2023-04-07 17:40 UTC, evkenny commented
Извините, вы могли бы подсказать где? я все пароли замаскировал.
Или логины тоже считается?

2023-04-08 08:45 UTC, pluhin commented
> Извините, вы могли бы подсказать где? я все пароли замаскировал. Или логины тоже считается?

Here 
![image](https://user-images.githubusercontent.com/8258487/230712429-cd519dc9-663d-42a2-aec0-d27d9dcbb699.png)

if you are fine with sharing "Company email password", then I can merge. 
Please check there is fake username/pass in your commit, or confirm, then i cam merge

2023-04-09 11:14 UTC, evkenny commented
Да, в последующих я его тоже маскировал. GitGuardian продолжает висеть из-за предыдущих коммитов. И также это ненужный mail

2023-04-09 16:40 UTC, pluhin approved these changes

2023-04-09 16:40 UTC, merged