Md sa2 25 23
pluhin/sa.it-academy.by pull request #2503
Opened 2023-09-26 13:30 UTC by AntonIvanovDevOps

2023-09-26 18:05 UTC, pluhin requested changes

2023-09-26 21:50 UTC, AntonIvanovDevOps commented
I changed script  and README file(URL didn't work).

2023-09-26 21:51 UTC, AntonIvanovDevOps commented on Anton_Ivanov/03.GIT.Hosting/README.md
> +## Script for automation pushing to GitHub
I changed script and fixed links in README file.

2023-09-27 13:52 UTC, pluhin approved these changes
Good, approved

2023-09-27 13:52 UTC, merged