Md sa2 25 23
pluhin/sa.it-academy.by pull request #2516
Opened 2023-10-03 10:23 UTC by SergeyKravchuk

2023-10-04 08:43 UTC, pluhin requested changes

2023-10-04 08:43 UTC, pluhin commented on Sergey_Kravchuk
> +
please remove this file, all files should be inside your folder

2023-10-04 08:43 UTC, pluhin commented on Sergey_kravchuk/02.Git.Local/README.md
> +# git clone https://github.com/SergeyKravchuk/sa.it-academy.by
task is not finished

2023-10-04 10:12 UTC, SergeyKravchuk commented on Sergey_Kravchuk
> +
не вижу этот файл через Bash
![image](https://github.com/pluhin/sa.it-academy.by/assets/145394684/11d9fc7b-e535-496e-80fd-f00a30c6b5c7)

2023-10-04 10:18 UTC, SergeyKravchuk commented on Sergey_kravchuk/02.Git.Local/README.md
> +# git clone https://github.com/SergeyKravchuk/sa.it-academy.by
write please what else I have to do

2023-10-08 17:40 UTC, pluhin requested changes
to many commits in one PR, please squash them to one
https://www.git-tower.com/learn/git/faq/git-squash#:~:text=In%20case%20you%20are%20using,option%20from%20the%20contextual%20menu.

2023-10-08 17:40 UTC, pluhin commented on Sergey_kravchuk/02.Git.Local/README.md
> +# 265  cd c/Users/s.kravchuk/
This history is history of your commands how prepare home work, but not home work itself

I need list commands, how you did this: https://github.com/pluhin/sa.it-academy.by/wiki/02.-GIT.-Local

2023-10-11 16:40 UTC, pluhin requested changes

2023-10-11 16:40 UTC, pluhin commented on README.md
> +#  #############DESCRIPTION OF MY PROJECT######################
To many commits, and changes not in your files

2023-10-12 19:10 UTC, closed without merging