HM2
pluhin/sa.it-academy.by pull request #2551
Opened 2023-10-17 20:47 UTC by SergeyKravchuk

2023-10-19 06:45 UTC, pluhin requested changes
Please squash commits, 37 commits is too much for one PR

2023-10-19 06:45 UTC, pluhin commented on README.md
please revert this change, we need this file

2023-10-19 08:42 UTC, SergeyKravchuk reviewed
revert

2023-10-29 17:45 UTC, pluhin commented
> > revert
> 
> Good, only squash is left

please make squash/fixup 
https://www.freecodecamp.org/news/git-squash-commits/

2023-12-11 10:52 UTC, closed without merging