Add Homework 2 in right branch
pluhin/sa.it-academy.by pull request #2804
Opened 2024-10-02 17:45 UTC by Maks-Bbb

2024-10-02 19:12 UTC, Maks-Bbb commented
I reviewed only the second lesson, but I didn't look at the third where you talked about the correct correction of the pull request. Therefore, I made a new one, and did not modify the old one. Now I will remember this and I will continue to try to make changes, not create a new one.

2024-10-03 11:55 UTC, pluhin requested changes

2024-10-03 11:55 UTC, pluhin commented on Maksim_Bogdanovich/README.md
> +...bash
wrong quotes, should be ``` 
ref: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

2024-10-07 07:50 UTC, pluhin approved these changes

2024-10-07 07:50 UTC, merged