11.Kubernetes.Basic.Objects.Full
pluhin/sa.it-academy.by pull request #2847
Opened 2024-11-04 16:06 UTC by Pro100chok91

2024-11-06 07:26 UTC, pluhin requested changes

2024-11-06 07:26 UTC, pluhin commented on Kirill_Fadeev/11.Kubernetes.Basic.Objects/README.md
> +```bash
it is yaml, not bash

2024-11-06 07:26 UTC, pluhin commented on Kirill_Fadeev/11.Kubernetes.Basic.Objects/README.md
> +  type: LoadBalancer
please remove, if you are not going to use loadbalancer

2024-11-06 11:22 UTC, Pro100chok91 commented on Kirill_Fadeev/11.Kubernetes.Basic.Objects/README.md
> +```bash
fixed

2024-11-06 11:23 UTC, Pro100chok91 commented
Added Homework 12.

2024-11-06 13:11 UTC, pluhin approved these changes

2024-11-10 11:12 UTC, pluhin approved these changes

2024-11-10 11:12 UTC, merged