sholomitski 2 task
pluhin/sa.it-academy.by pull request #2870
Opened 2024-12-22 16:01 UTC by xaos613

Added file 02.GIT.Local.md with solution of 2 task

2024-12-22 16:47 UTC, pluhin requested changes

2024-12-22 16:47 UTC, pluhin commented on Sholomitski Dmitry/02.Git.Local/02.GIT.Local.md
> +# Homework Assignment 1: Initializing a Local Repository
Please remove white space from folder name

2024-12-22 16:52 UTC, xaos613 commented
Name changed

2024-12-23 09:59 UTC, xaos613 commented on Sholomitski Dmitry/02.Git.Local/02.GIT.Local.md
> +# Homework Assignment 1: Initializing a Local Repository
Removed

2024-12-23 11:19 UTC, pluhin approved these changes

2024-12-23 11:20 UTC, merged